CREATE TABLE NEWS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LINK VARCHAR(2000),
    TITLE TEXT,
    CONTENT TEXT,
    CREATED_AT TIMESTAMP
);

CREATE TABLE LINKS_TO_BE_PROCESSED(
    LINK VARCHAR(2000)
);

CREATE TABLE LINK_ALREADY_PROCESSED(
    LINK VARCHAR(2000)
);


